dan-chez/car_manager_ui

- example/lib/component_model.dart
- example/lib/component_view.dart
- example/lib/components_showcases.dart
- example/lib/main.dart
- example/lib/navigation/go_router_provider.dart
- example/lib/showcases/button_showcase.dart
- example/pubspec.lock
- example/pubspec.yaml
- example/test/widget_test.dart
- lib/carmanager_ui.dart
- lib/src/constants/int_constants.dart
- lib/src/constants/text_constants.dart
- lib/src/utils/cm_scroll_behavior.dart
[CARMAN-208](https://danchez.atlassian.net/browse/CARMAN-208)
Implement go router package to navigate component showcases.
https://github.com/user-attachments/assets/bbd6cfef-2c65-42bf-b8ef-1c9553515059
> [CARMAN-208] Implement go router

- .github/workflows/dart.yml
- test/src/components/buttons/primary_button_test.dart
[CARMAN-209](https://danchez.atlassian.net/browse/CARMAN-209)
Added initial setup for automated testing with GitHub Actions, including Flutter setup and code analysis.
Implemented unit tests for the PrimaryButton widget as a example for test widget.
> [CARMAN-209] Implement GitHub actions

- example/lib/showcases/button_showcase.dart
- lib/carmanager_ui.dart
- lib/src/constants/button_constants.dart
- lib/src/constants/cm_icons.dart
- lib/src/constants/text_constants.dart
- test/src/components/buttons/primary_button_test.dart
[CARMAN-191](https://danchez.atlassian.net/browse/CARMAN-191)
All missing cases for PrimaryButton have been added.
[Screen_recording_20240805_122325.webm](https://github.com/user-attachments/assets/34085b1b-66fb-4880-8a1c-0e0f023393cd)
> [CARMAN-191] Move Buttons

- example/lib/components_showcases.dart
- example/lib/navigation/go_router_provider.dart
- example/lib/showcases/rich_text_showcase.dart
- lib/carmanager_ui.dart
- lib/src/components/cm_rich_text.dart
- lib/src/constants/string_constants.dart
- test/src/components/cm_rich_text_test.dart
[CARMAN-217](https://danchez.atlassian.net/browse/CARMAN-217)
Moved CMRichText Class to UI Package: Refactored the codebase to reduce redundant code.
Implemented comprehensive unit tests, covering various scenarios.
https://github.com/user-attachments/assets/079fd4c4-b2fa-4dd5-a075-bd7d59587b98
> [CARMAN-217] CMRichText added to package

- example/lib/components_showcases.dart
- example/lib/navigation/go_router_provider.dart
- example/lib/showcases/icon_button_showcase.dart
- lib/carmanager_ui.dart
- lib/src/components/buttons/cm_icon_button.dart
- test/src/components/buttons/cm_icon_button_test.dart
[CARMAN-214](https://danchez.atlassian.net/browse/CARMAN-214)
Move CMIconButton to package.
> [CARMAN-214] Move Icon Button To Package

- example/lib/components_showcases.dart
- example/lib/navigation/go_router_provider.dart
- example/lib/showcases/dropdown_showcase.dart
- lib/carmanager_ui.dart
- lib/src/components/dropdown/cm_dropdown.dart
- lib/src/constants/cm_icons.dart
- test/src/components/dropdown/cm_dropdown_test.dart
[CARMAN-212](https://danchez.atlassian.net/browse/CARMAN-212)
CMDropdown moved to UI package
https://github.com/user-attachments/assets/16cd006d-68d6-43f5-af32-4dc5fac9a61d
> [CARMAN-212] CMDropdown moved to UI package

- example/lib/showcases/rich_text_showcase.dart
[CARMAN-224] (https://danchez.atlassian.net/browse/CARMAN-224)
Add more usage examples to RichText showcase
> [CARMAN-224] Add more usage examples to RichText showcase

- README.md
> [SUPPORT] Fix code coverage branch in README

- example/pubspec.lock
- pubspec.yaml
Bump packages versions to publish first pub.dev version.
> [SUPPORT* Bumb packages versions

- CHANGELOG.md
- README.md
> Support: Fix minor release errors

- CHANGELOG.md
- example/pubspec.lock
- pubspec.yaml
> Support: Changelog modified for 0.0.1+1 version

- .github/pull_request_template.md
> Support: Update pull_request_template.md with checklist

- .github/workflows/pre_publish.yml
- .github/workflows/publish.yml
[CARMAN-249](https://danchez.atlassian.net/browse/CARMAN-249)
Continuous delivery with github actions and pub.dev
Everytime a new tag is pushed with this format "vX.X.X" or "vX.X.X+X" a new pipeline will be launched to publish a new package version in pub.dev
> [CARMAN-249] Continuous delivery with github actions and pub.dev

- .gitignore
Modify .gitignore file to fix CD pipeline
> Support: Modify .gitignore file to fix CD pipeline

- CHANGELOG.md
- pubspec.yaml
> [Support] Bump package version

- .github/workflows/pre_publish.yml
- pubspec.yaml
> Support: Add pre publish workflow for release branches

- .github/workflows/pre_publish.yml
- pubspec.yaml
> Support: Release 0.0.1+2

- example/pubspec.lock
- pubspec.yaml
> Support: Fix packages versions

- CHANGELOG.md
- pubspec.yaml
> [Support] Bump package version 0.0.1+3

- CHANGELOG.md
- example/pubspec.lock
- pubspec.yaml
> Support: Release 0.0.1+3

- lib/carmanager_ui.dart
> Support: Export CloseIconButton

- CHANGELOG.md
- pubspec.yaml
> [Support] Bump package version 0.0.2

- CHANGELOG.md
- pubspec.yaml
> Support: Release 0.0.2

- .github/workflows/car_manager_ui.yml
- .github/workflows/pre_publish.yml
- .github/workflows/publish_artifacts.yml
This PR adds a GitHub Actions workflow to automate building and publishing test APKs for Car Manager UI on pushes to the develop branch. It includes Flutter setup, APK build and artifact upload. Also, modifies the gradle file and the build command to be executed from the example folder.
> [SUPPORT] Continuous delivery for publish example app android APK

- example/lib/navigation/go_router_provider.dart
- example/lib/showcases/current_vehicle_card_showcase.dart
- example/lib/showcases/selectable_service_type_showcase.dart
- example/lib/showcases/selectable_vehicle_type_showcase.dart
- example/lib/showcases/vehicle_info_card_showcase.dart
- example/lib/showcases/warning_info_showcase.dart
- lib/src/components/cm_switch.dart
- lib/src/components/current_vehicle_card.dart
- lib/src/components/expenses_line_chart/helpers/line_chart_bar_data_helper.dart
- lib/src/components/vehicle_info_card/vehicle_info_card.dart
- lib/src/components/warning_info.dart
- lib/src/utils/cm_raw_dialog_route.dart
- lib/src/utils/extensions/color_extensions.dart
- test/src/components/buttons/cm_date_button_test.dart
- test/src/components/cm_switch_test.dart
- test/src/components/current_vehicle_card_test.dart
- test/src/components/expenses_line_chart/utils/expenses_line_chart_utils_test.dart
- test/src/components/selectable_service_type/selectable_service_type_test.dart
- test/src/components/selectable_vehicle_type/selectable_vehicle_type_test.dart
- test/src/components/text_field/money_text_field/money_text_editing_controller_test.dart
- test/src/components/vehicle_info_card/vehicle_info_card_test.dart
- test/src/components/warning_info_test.dart
- test/src/utils/extensions/color_extensions_test.dart
> [SUPPORT] Dart format in project

- .github/workflows/car_manager_ui.yml
- .github/workflows/pre_publish.yml
- .github/workflows/publish_artifacts.yml
- example/android/app/build.gradle
- example/android/settings.gradle
Bump Java version to 17 in the test app. Additionally, this PR updates the Flutter version to 3.29.2.
> [SUPPORT] Bump java version to 17 in test app and Flutter version to 3.29.2

- .github/workflows/car_manager_ui.yml
- .github/workflows/pre_publish.yml
- .github/workflows/publish_artifacts.yml
- CHANGELOG.md
- example/android/app/build.gradle
- example/android/settings.gradle
- example/lib/showcases/page_title_showcase.dart
- example/lib/showcases/text_field_showcase.dart
- example/pubspec.lock
- lib/src/components/cm_info_card.dart
- lib/src/components/cm_page_title.dart
- lib/src/components/text_field/cm_multiline_text_field.dart
- lib/src/components/text_field/cm_text_field.dart
- lib/src/components/text_field/text_field_base.dart
- lib/src/constants/app_colors_constants.dart
- lib/src/constants/cm_dimens.dart
- lib/src/constants/cm_icons.dart
- lib/src/constants/text_style_constants.dart
- pubspec.yaml
- test/src/components/page_title/page_title_test.dart
- test/src/components/text_field/cm_multiline_text_field_test.dart
- test/src/components/text_field/cm_text_field_test.dart
> Support: Release 1.0.1

- example/lib/showcases/selectable_service_type_showcase.dart
- example/pubspec.lock
- lib/src/components/selectable_service_type/selectable_service_type.dart
- test/src/components/selectable_service_type/selectable_service_type_test.dart
[CARMAN-321](https://danchez.atlassian.net/browse/CARMAN-321)
The ability to make an initial selection has been added to the SelectableServiceType widget.
https://github.com/user-attachments/assets/842b2f60-09d9-43ec-8b9b-5934f3111b6a
> [CARMAN-321] Initial selection added to SelectableServiceType

- example/lib/components_showcases.dart
- example/lib/navigation/go_router_provider.dart
- example/lib/showcases/profile_menu_item_showcase.dart
- lib/carmanager_ui.dart
- lib/src/components/profile_menu_item/profile_menu_item.dart
- lib/src/components/profile_menu_item/profile_menu_item_model.dart
- test/src/components/profile_menu_item/profile_menu_item_test.dart
[CARMAN-200](https://danchez.atlassian.net/browse/CARMAN-200)
Add profile menu item widget.
> [CARMAN-200] Profile Menu Item

- example/lib/showcases/toggle_button_showcase.dart
- lib/src/components/cm_toggle_button.dart
[CARMAN-198](https://danchez.atlassian.net/browse/CARMAN-198)
Refactor toggle button
https://github.com/user-attachments/assets/e11b0031-8db3-4c4a-a492-ae0b46f969b2
> [CARMAN-198] Refactor Toggle Button

- .github/workflows/deploy_firebase_distribution.yml
[CARMAN-314](https://danchez.atlassian.net/browse/CARMAN-314)
Example app continuous delivery to Firebase Distribution.
> [CARMAN-314] Setup CD To Firebase Distribution

- .github/workflows/deploy_firebase_distribution.yml
- CHANGELOG.md
- example/lib/components_showcases.dart
- example/lib/navigation/go_router_provider.dart
- example/lib/showcases/profile_menu_item_showcase.dart
- example/lib/showcases/selectable_service_type_showcase.dart
- example/lib/showcases/selectable_vehicle_type_showcase.dart
- example/lib/showcases/toggle_button_showcase.dart
- example/pubspec.lock
- lib/carmanager_ui.dart
- lib/src/components/cm_toggle_button.dart
- lib/src/components/profile_menu_item/profile_menu_item.dart
- lib/src/components/profile_menu_item/profile_menu_item_model.dart
- lib/src/components/selectable_service_type/selectable_service_type.dart
- lib/src/components/selectable_vehicle_type/selectable_vehicle_type.dart
- pubspec.yaml
- test/src/components/profile_menu_item/profile_menu_item_test.dart
- test/src/components/selectable_service_type/selectable_service_type_test.dart
- test/src/components/selectable_vehicle_type/selectable_vehicle_type_test.dart
> Support: Release 1.1.0

- example/lib/components_showcases.dart
- example/lib/navigation/go_router_provider.dart
- example/lib/showcases/cm_info_panel_showcase.dart
- lib/carmanager_ui.dart
- lib/src/components/cm_info_panel.dart
- lib/src/constants/decoration_constants.dart
- test/src/components/cm_info_panel_test.dart
- test/src/utils/finders.dart
[CARMAN-322](https://danchez.atlassian.net/browse/CARMAN-322)
Add CMInfoPanel
> [CARMAN-322] Add CMInfoPanel

- .github/workflows/car_manager_ui.yml
- .github/workflows/deploy_firebase_distribution.yml
- .github/workflows/pre_publish.yml
- example/pubspec.lock
- pubspec.yaml
Because in the new version of Flutter, the flutter_localizations package required version 0.20.2 of intl, the version had to be bumped in the project.
> [SUPPORT] Bump Intl Version

- .github/workflows/car_manager_ui.yml
- .github/workflows/deploy_firebase_distribution.yml
- .github/workflows/pre_publish.yml
- CHANGELOG.md
- example/pubspec.lock
- pubspec.yaml
> Support: Release 1.2.1

- example/android/gradle/wrapper/gradle-wrapper.properties
- example/android/settings.gradle
- example/pubspec.lock
Upgrade Gradle and Android plugin versions for the test app, and update the main dependency version. No functional changes.
> [NO-TICKET] Bump android testapp gradle version

- CHANGELOG.md
- example/lib/showcases/vehicle_info_card_showcase.dart
- example/pubspec.lock
- lib/src/components/vehicle_info_card/vehicle_info_card.dart
- pubspec.yaml
- test/src/components/vehicle_info_card/vehicle_info_card_test.dart
> Support: Release 1.2.3

- CHANGELOG.md
- example/lib/showcases/dialogs_showcase.dart
- lib/src/components/cm_rich_text.dart
- lib/src/components/dialogs/confirm/confirm_dialog.dart
- lib/src/components/dialogs/confirm/confirm_dialog_data.dart
- pubspec.yaml
> Support: Release 1.3.0

- example/android/settings.gradle
- example/pubspec.lock
Bumped the com.android.application plugin version from 8.2.1 to 8.3.0 in settings.gradle to ensure compatibility with the latest Android build tools.
> [NO-TICKET] Update Android Gradle plugin to 8.3.0
